"""
Contract tests for POST /api/v1/employees.
Cases:
- Admin creates Employee with valid payload → 201
- employee_code is auto-generated and unique if omitted
- Weak/short password → 422
- Missing required fields → 422
"""

import uuid
import pytest
from app.models.role import Role
from app.models.department import Department
from app.models.employee import Employee
from app.core.security import get_password_hash


def _ensure_setup(db):
    """Set up admin+dept inside the function-scoped SQLite DB."""
    admin_role = db.query(Role).filter(Role.role_name == "Admin").first()
    if not admin_role:
        admin_role = Role(role_name="Admin")
        db.add(admin_role)
        db.commit()

    emp_role = db.query(Role).filter(Role.role_name == "Employee").first()
    if not emp_role:
        emp_role = Role(role_name="Employee")
        db.add(emp_role)
        db.commit()

    # Use test-unique department code to avoid UNIQUE violations across tests
    dept_code = "IT-EMP"
    dept = db.query(Department).filter(Department.department_code == dept_code).first()
    if not dept:
        dept = Department(
            name="IT Employee Test", department_code=dept_code, is_active=True
        )
        db.add(dept)
        db.commit()

    admin = db.query(Employee).filter(Employee.email == "emp_adm@emptest.com").first()
    if not admin:
        admin = Employee(
            employee_code="EMP-ADM-ECC",
            full_name="Emp Contract Admin",
            email="emp_adm@emptest.com",
            password_hash=get_password_hash("TaskSync@2026"),
            role_id=admin_role.id,
            department_id=dept.id,
            is_active=True,
        )
        db.add(admin)
        db.commit()
        db.refresh(admin)

    return admin_role, emp_role, dept, admin


def _admin_token(client):
    r = client.post(
        "/api/v1/auth/login",
        data={"username": "emp_adm@emptest.com", "password": "TaskSync@2026"},
    )
    assert r.status_code == 200, f"Login failed: {r.json()}"
    return r.json()["access_token"]


# ── Tests ─────────────────────────────────────────────────────────────────────


def test_admin_creates_employee_valid(client, db):
    """Admin creates a valid Employee → 201 with populated employee_code."""
    admin_role, emp_role, dept, admin = _ensure_setup(db)
    emp_role_id = emp_role.id
    dept_id = dept.id
    token = _admin_token(client)
    headers = {"Authorization": f"Bearer {token}"}

    resp = client.post(
        "/api/v1/employees",
        json={
            "full_name": "Nguyễn Văn A",
            "email": f"nva-{uuid.uuid4().hex[:6]}@enterprise.com",
            "password": "TaskSync@2026",
            "role_id": emp_role_id,
            "department_id": dept_id,
        },
        headers=headers,
    )
    assert resp.status_code == 201, resp.json()
    data = resp.json()
    assert data["full_name"] == "Nguyễn Văn A"
    assert "employee_code" in data and data["employee_code"]


def test_employee_code_autogenerated_and_unique(client, db):
    """Two Employee creations without employee_code → both get distinct codes."""
    admin_role, emp_role, dept, admin = _ensure_setup(db)
    emp_role_id = emp_role.id
    dept_id = dept.id
    token = _admin_token(client)
    headers = {"Authorization": f"Bearer {token}"}

    resp1 = client.post(
        "/api/v1/employees",
        json={
            "full_name": "Trần Thị B",
            "email": f"ttb-{uuid.uuid4().hex[:6]}@enterprise.com",
            "password": "TaskSync@2026",
            "role_id": emp_role_id,
            "department_id": dept_id,
        },
        headers=headers,
    )
    resp2 = client.post(
        "/api/v1/employees",
        json={
            "full_name": "Lê Văn C",
            "email": f"lvc-{uuid.uuid4().hex[:6]}@enterprise.com",
            "password": "TaskSync@2026",
            "role_id": emp_role_id,
            "department_id": dept_id,
        },
        headers=headers,
    )

    assert resp1.status_code == 201, resp1.json()
    assert resp2.status_code == 201, resp2.json()

    code1 = resp1.json()["employee_code"]
    code2 = resp2.json()["employee_code"]
    assert code1 != code2, "Auto-generated codes must be unique"


def test_weak_password_returns_422(client, db):
    """Password shorter than minimum requirement → 422."""
    admin_role, emp_role, dept, admin = _ensure_setup(db)
    emp_role_id = emp_role.id
    dept_id = dept.id
    token = _admin_token(client)
    headers = {"Authorization": f"Bearer {token}"}

    resp = client.post(
        "/api/v1/employees",
        json={
            "full_name": "Pham Van D",
            "email": f"pvd-{uuid.uuid4().hex[:6]}@enterprise.com",
            "password": "123",  # too short / weak
            "role_id": emp_role_id,
            "department_id": dept_id,
        },
        headers=headers,
    )
    assert resp.status_code == 422, resp.json()


def test_missing_required_fields_returns_422(client, db):
    """Omitting required `email`, `password` and `role_id` → 422."""
    admin_role, emp_role, dept, admin = _ensure_setup(db)
    token = _admin_token(client)
    headers = {"Authorization": f"Bearer {token}"}

    resp = client.post(
        "/api/v1/employees",
        json={
            "full_name": "Incomplete Employee",
            # email, password, role_id all missing
        },
        headers=headers,
    )
    assert resp.status_code == 422, resp.json()
