from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

# Patch Alembic's foreign key comparison to be a no-op to prevent false positive FK/schema checks on SQL Server
import alembic.autogenerate.compare.constraints as alembic_constraints
from alembic.util.langhelpers import PriorityDispatchResult

def dummy_compare(*args, **kwargs):
    return PriorityDispatchResult.CONTINUE

alembic_constraints._compare_foreign_keys.__code__ = dummy_compare.__code__

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Thay bằng import Base từ app của bạn
from app.database import Base
import app.models  # ÉP ALEMBIC LOAD TOÀN BỘ MODEL ĐỂ KHÔNG BỊ TRỐNG MIGRATION

target_metadata = Base.metadata


def include_object(object, name, type, reflected, compare_to):
    """Filter out autogenerated objects if needed (default to True)."""
    return True


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_server_default=False,
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    from app.config import settings  # Import cấu hình từ file của bạn
    
    configuration = config.get_section(config.config_ini_section) or {}
    configuration["sqlalchemy.url"] = settings.SQLALCHEMY_DATABASE_URI
    
    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection, 
            target_metadata=target_metadata,
            compare_server_default=False,
            include_object=include_object,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
