"""add department_id and team_id to projects

Revision ID: 05252bd1d012
Revises: c7f4a2b8d901
Create Date: 2026-07-31 16:19:04.806646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05252bd1d012'
down_revision: Union[str, Sequence[str], None] = 'c7f4a2b8d901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dbo_backlog_items_project_id'), table_name='backlog_items')
    op.drop_index(op.f('ix_dbo_backlog_items_sprint_id'), table_name='backlog_items')
    op.drop_index(op.f('ix_dbo_discussion_replies_topic_id'), table_name='discussion_replies')
    op.drop_index(op.f('ix_dbo_discussion_topics_project_id'), table_name='discussion_topics')
    op.add_column('projects', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('team_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_dbo_sprint_snapshots_sprint_id'), table_name='sprint_snapshots')
    op.drop_index(op.f('ix_dbo_sprints_project_id'), table_name='sprints')
    op.drop_index(op.f('ix_dbo_task_attachments_feedback_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_dbo_task_attachments_reply_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_dbo_task_attachments_topic_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_dbo_tasks_sprint_id'), table_name='tasks')
    op.drop_index(op.f('ix_dbo_user_feedback_submitter_id'), table_name='user_feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dbo_user_feedback_submitter_id'), 'user_feedback', ['submitter_id'], unique=False)
    op.create_index(op.f('ix_dbo_tasks_sprint_id'), 'tasks', ['sprint_id'], unique=False)
    op.create_index(op.f('ix_dbo_task_attachments_topic_id'), 'task_attachments', ['topic_id'], unique=False)
    op.create_index(op.f('ix_dbo_task_attachments_reply_id'), 'task_attachments', ['reply_id'], unique=False)
    op.create_index(op.f('ix_dbo_task_attachments_feedback_id'), 'task_attachments', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_dbo_sprints_project_id'), 'sprints', ['project_id'], unique=False)
    op.create_index(op.f('ix_dbo_sprint_snapshots_sprint_id'), 'sprint_snapshots', ['sprint_id'], unique=False)
    op.drop_column('projects', 'team_id')
    op.drop_column('projects', 'department_id')
    op.create_index(op.f('ix_dbo_discussion_topics_project_id'), 'discussion_topics', ['project_id'], unique=False)
    op.create_index(op.f('ix_dbo_discussion_replies_topic_id'), 'discussion_replies', ['topic_id'], unique=False)
    op.create_index(op.f('ix_dbo_backlog_items_sprint_id'), 'backlog_items', ['sprint_id'], unique=False)
    op.create_index(op.f('ix_dbo_backlog_items_project_id'), 'backlog_items', ['project_id'], unique=False)
    # ### end Alembic commands ###
