"""init_db_v2_final

Revision ID: f4e146c8eb61
Revises: 
Create Date: 2026-07-04 03:26:16.005915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e146c8eb61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_code'),
    sa.UniqueConstraint('name'),
    schema='dbo'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name'),
    schema='dbo'
    )
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('team_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['dbo.departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_code'),
    schema='dbo'
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_first_login', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_logout', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['dbo.departments.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['dbo.employees.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['dbo.roles.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['dbo.teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_code'),
    schema='dbo'
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('employee_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['dbo.employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_index(op.f('ix_dbo_audit_logs_action'), 'audit_logs', ['action'], unique=False, schema='dbo')
    op.create_index(op.f('ix_dbo_audit_logs_employee_email'), 'audit_logs', ['employee_email'], unique=False, schema='dbo')
    op.create_index(op.f('ix_dbo_audit_logs_id'), 'audit_logs', ['id'], unique=False, schema='dbo')
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['dbo.employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_index(op.f('ix_dbo_notifications_id'), 'notifications', ['id'], unique=False, schema='dbo')
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'Planning'"), nullable=False),
    sa.Column('priority', sa.String(length=20), server_default=sa.text("'Medium'"), nullable=False),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['dbo.employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code'),
    schema='dbo'
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['dbo.employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['dbo.employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_table('vacations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'Pending'"), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['dbo.employees.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['dbo.employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_index(op.f('ix_dbo_vacations_id'), 'vacations', ['id'], unique=False, schema='dbo')
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['dbo.employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['dbo.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), server_default=sa.text("'Medium'"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'To Do'"), nullable=False),
    sa.Column('story_points', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['dbo.employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['dbo.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_table('task_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['dbo.employees.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['dbo.tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_table('task_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['dbo.tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['dbo.employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_table('task_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['dbo.tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_table('task_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['dbo.employees.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['dbo.tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_comments', schema='dbo')
    op.drop_table('task_checklists', schema='dbo')
    op.drop_table('task_attachments', schema='dbo')
    op.drop_table('task_assignments', schema='dbo')
    op.drop_table('tasks', schema='dbo')
    op.drop_table('project_members', schema='dbo')
    op.drop_index(op.f('ix_dbo_vacations_id'), table_name='vacations', schema='dbo')
    op.drop_table('vacations', schema='dbo')
    op.drop_table('user_sessions', schema='dbo')
    op.drop_table('refresh_tokens', schema='dbo')
    op.drop_table('projects', schema='dbo')
    op.drop_index(op.f('ix_dbo_notifications_id'), table_name='notifications', schema='dbo')
    op.drop_table('notifications', schema='dbo')
    op.drop_index(op.f('ix_dbo_audit_logs_id'), table_name='audit_logs', schema='dbo')
    op.drop_index(op.f('ix_dbo_audit_logs_employee_email'), table_name='audit_logs', schema='dbo')
    op.drop_index(op.f('ix_dbo_audit_logs_action'), table_name='audit_logs', schema='dbo')
    op.drop_table('audit_logs', schema='dbo')
    op.drop_table('employees', schema='dbo')
    op.drop_table('teams', schema='dbo')
    op.drop_table('token_blacklist', schema='dbo')
    op.drop_table('roles', schema='dbo')
    op.drop_table('departments', schema='dbo')
    # ### end Alembic commands ###
