"""alter_notification_unicode

Revision ID: f69319655bb9
Revises: f4e146c8eb61
Create Date: 2026-07-04 04:08:03.749302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69319655bb9'
down_revision: Union[str, Sequence[str], None] = 'f4e146c8eb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__audit_log__emplo__59FA5E80'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'employees', ['employee_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.drop_constraint(op.f('FK__employees__depar__534D60F1'), 'employees', type_='foreignkey')
    op.drop_constraint(op.f('FK__employees__team___5629CD9C'), 'employees', type_='foreignkey')
    op.drop_constraint(op.f('FK__employees__manag__5441852A'), 'employees', type_='foreignkey')
    op.drop_constraint(op.f('FK__employees__role___5535A963'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.create_foreign_key(None, 'employees', 'roles', ['role_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.create_foreign_key(None, 'employees', 'employees', ['manager_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.create_foreign_key(None, 'employees', 'teams', ['team_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.drop_constraint(op.f('FK__notificat__emplo__5EBF139D'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'employees', ['employee_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.drop_constraint(op.f('FK__project_m__proje__7B5B524B'), 'project_members', type_='foreignkey')
    op.drop_constraint(op.f('FK__project_m__emplo__7A672E12'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'employees', ['employee_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.drop_constraint(op.f('FK__projects__create__6754599E'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'employees', ['created_by'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.drop_constraint(op.f('FK__refresh_t__emplo__6C190EBB'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'employees', ['employee_id'], ['id'], source_schema='dbo', referent_schema='dbo', ondelete='CASCADE')
    op.drop_constraint(op.f('FK__task_assi__task___09A971A2'), 'task_assignments', type_='foreignkey')
    op.drop_constraint(op.f('FK__task_assi__emplo__08B54D69'), 'task_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'task_assignments', 'tasks', ['task_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.create_foreign_key(None, 'task_assignments', 'employees', ['employee_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.drop_constraint(op.f('FK__task_atta__uploa__0E6E26BF'), 'task_attachments', type_='foreignkey')
    op.drop_constraint(op.f('FK__task_atta__task___0D7A0286'), 'task_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'task_attachments', 'tasks', ['task_id'], ['id'], source_schema='dbo', referent_schema='dbo', ondelete='CASCADE')
    op.create_foreign_key(None, 'task_attachments', 'employees', ['uploaded_by_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.drop_constraint(op.f('FK__task_chec__task___123EB7A3'), 'task_checklists', type_='foreignkey')
    op.create_foreign_key(None, 'task_checklists', 'tasks', ['task_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.drop_constraint(op.f('FK__task_comm__task___17036CC0'), 'task_comments', type_='foreignkey')
    op.drop_constraint(op.f('FK__task_comm__emplo__160F4887'), 'task_comments', type_='foreignkey')
    op.create_foreign_key(None, 'task_comments', 'employees', ['employee_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.create_foreign_key(None, 'task_comments', 'tasks', ['task_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.drop_constraint(op.f('FK__tasks__project_i__04E4BC85'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('FK__tasks__created_b__03F0984C'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.create_foreign_key(None, 'tasks', 'employees', ['created_by'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.drop_constraint(op.f('FK__teams__departmen__49C3F6B7'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'departments', ['department_id'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.drop_constraint(op.f('FK__user_sess__emplo__70DDC3D8'), 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'employees', ['employee_id'], ['id'], source_schema='dbo', referent_schema='dbo', ondelete='CASCADE')
    op.drop_constraint(op.f('FK__vacations__appro__75A278F5'), 'vacations', type_='foreignkey')
    op.drop_constraint(op.f('FK__vacations__reque__76969D2E'), 'vacations', type_='foreignkey')
    op.create_foreign_key(None, 'vacations', 'employees', ['requested_by'], ['id'], source_schema='dbo', referent_schema='dbo')
    op.create_foreign_key(None, 'vacations', 'employees', ['approved_by'], ['id'], source_schema='dbo', referent_schema='dbo')
    
    # Manually alter columns in notifications table to use NVARCHAR
    op.alter_column('notifications', 'title',
               existing_type=sa.String(length=200),
               type_=sa.Unicode(length=200),
               existing_nullable=False,
               schema='dbo')
    op.alter_column('notifications', 'message',
               existing_type=sa.String(length=1000),
               type_=sa.Unicode(length=1000),
               existing_nullable=False,
               schema='dbo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacations', schema='dbo', type_='foreignkey')
    op.drop_constraint(None, 'vacations', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__vacations__reque__76969D2E'), 'vacations', 'employees', ['requested_by'], ['id'])
    op.create_foreign_key(op.f('FK__vacations__appro__75A278F5'), 'vacations', 'employees', ['approved_by'], ['id'])
    op.drop_constraint(None, 'user_sessions', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__user_sess__emplo__70DDC3D8'), 'user_sessions', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'teams', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__teams__departmen__49C3F6B7'), 'teams', 'departments', ['department_id'], ['id'])
    op.drop_constraint(None, 'tasks', schema='dbo', type_='foreignkey')
    op.drop_constraint(None, 'tasks', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__tasks__created_b__03F0984C'), 'tasks', 'employees', ['created_by'], ['id'])
    op.create_foreign_key(op.f('FK__tasks__project_i__04E4BC85'), 'tasks', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'task_comments', schema='dbo', type_='foreignkey')
    op.drop_constraint(None, 'task_comments', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__task_comm__emplo__160F4887'), 'task_comments', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(op.f('FK__task_comm__task___17036CC0'), 'task_comments', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'task_checklists', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__task_chec__task___123EB7A3'), 'task_checklists', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'task_attachments', schema='dbo', type_='foreignkey')
    op.drop_constraint(None, 'task_attachments', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__task_atta__task___0D7A0286'), 'task_attachments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('FK__task_atta__uploa__0E6E26BF'), 'task_attachments', 'employees', ['uploaded_by_id'], ['id'])
    op.drop_constraint(None, 'task_assignments', schema='dbo', type_='foreignkey')
    op.drop_constraint(None, 'task_assignments', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__task_assi__emplo__08B54D69'), 'task_assignments', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(op.f('FK__task_assi__task___09A971A2'), 'task_assignments', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'refresh_tokens', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__refresh_t__emplo__6C190EBB'), 'refresh_tokens', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'projects', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__projects__create__6754599E'), 'projects', 'employees', ['created_by'], ['id'])
    op.drop_constraint(None, 'project_members', schema='dbo', type_='foreignkey')
    op.drop_constraint(None, 'project_members', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__project_m__emplo__7A672E12'), 'project_members', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(op.f('FK__project_m__proje__7B5B524B'), 'project_members', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'notifications', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__notificat__emplo__5EBF139D'), 'notifications', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(None, 'employees', schema='dbo', type_='foreignkey')
    op.drop_constraint(None, 'employees', schema='dbo', type_='foreignkey')
    op.drop_constraint(None, 'employees', schema='dbo', type_='foreignkey')
    op.drop_constraint(None, 'employees', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__employees__role___5535A963'), 'employees', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('FK__employees__manag__5441852A'), 'employees', 'employees', ['manager_id'], ['id'])
    op.create_foreign_key(op.f('FK__employees__team___5629CD9C'), 'employees', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('FK__employees__depar__534D60F1'), 'employees', 'departments', ['department_id'], ['id'])
    op.drop_constraint(None, 'audit_logs', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__audit_log__emplo__59FA5E80'), 'audit_logs', 'employees', ['employee_id'], ['id'])
    
    # Manually revert columns in notifications table to VARCHAR
    op.alter_column('notifications', 'title',
               existing_type=sa.Unicode(length=200),
               type_=sa.String(length=200),
               existing_nullable=False,
               schema='dbo')
    op.alter_column('notifications', 'message',
               existing_type=sa.Unicode(length=1000),
               type_=sa.String(length=1000),
               existing_nullable=False,
               schema='dbo')
    # ### end Alembic commands ###
