# 📂 FILE: app/core/error_codes.py

# 🔐 Category: Authentication & Authorization (AUTH_*)
AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"
AUTH_FORBIDDEN = "AUTH_FORBIDDEN"
AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
AUTH_TOKEN_BLACKLISTED = "AUTH_TOKEN_BLACKLISTED"
AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
AUTH_CLIENT_INVALID = "AUTH_CLIENT_INVALID"

# 👥 Category: Employee & HRM (EMPLOYEE_*)
EMPLOYEE_NOT_FOUND = "EMPLOYEE_NOT_FOUND"
EMPLOYEE_CODE_EXISTS = "EMPLOYEE_CODE_EXISTS"
EMPLOYEE_EMAIL_EXISTS = "EMPLOYEE_EMAIL_EXISTS"
EMPLOYEE_INACTIVE = "EMPLOYEE_INACTIVE"

# 📂 Category: Project Management (PROJECT_*)
PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
PROJECT_CODE_EXISTS = "PROJECT_CODE_EXISTS"
PROJECT_ACCESS_DENIED = "PROJECT_ACCESS_DENIED"

# 📋 Category: Task Management (TASK_*)
TASK_NOT_FOUND = "TASK_NOT_FOUND"
TASK_INVALID_STATUS = "TASK_INVALID_STATUS"
TASK_ASSIGNMENT_FAILED = "TASK_ASSIGNMENT_FAILED"

# 📁 Category: Files & Storage (FILE_*)
FILE_TOO_LARGE = "FILE_TOO_LARGE"
FILE_INVALID_TYPE = "FILE_INVALID_TYPE"
FILE_STORAGE_ERROR = "FILE_STORAGE_ERROR"
FILE_NOT_FOUND = "FILE_NOT_FOUND"

# 💾 Category: Database Errors (DATABASE_*)
DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
DATABASE_INTEGRITY_VIOLATION = "DATABASE_INTEGRITY_VIOLATION"
DATABASE_TRANSACTION_ERROR = "DATABASE_TRANSACTION_ERROR"

# ⚙️ Category: System-wide Errors (SYSTEM_*)
SYSTEM_INTERNAL_ERROR = "SYSTEM_INTERNAL_ERROR"
SYSTEM_UNHANDLED_EXCEPTION = "SYSTEM_UNHANDLED_EXCEPTION"
SYSTEM_SERVICE_UNAVAILABLE = "SYSTEM_SERVICE_UNAVAILABLE"

# 🔍 Category: Schema & Validation (VALIDATION_*)
VALIDATION_REQUEST_FAILED = "VALIDATION_REQUEST_FAILED"
VALIDATION_TYPE_MISMATCH = "VALIDATION_TYPE_MISMATCH"
VALIDATION_MISSING_FIELD = "VALIDATION_MISSING_FIELD"
